/**
 * Day 20: MCP Server Builder - Interactive Demo
 */

// Tab Navigation
document.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        const tabId = btn.dataset.tab;

        // Update buttons
        document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');

        // Update panels
        document.querySelectorAll('.tab-panel').forEach(p => p.classList.remove('active'));
        document.getElementById(tabId).classList.add('active');
    });
});

// Toast notification
function showToast(message) {
    const toast = document.getElementById('toast');
    toast.textContent = message;
    toast.classList.add('show');
    setTimeout(() => toast.classList.remove('show'), 2000);
}

// Copy to clipboard
async function copyToClipboard(text) {
    try {
        await navigator.clipboard.writeText(text);
        showToast('Copied to clipboard!');
    } catch (err) {
        console.error('Failed to copy:', err);
    }
}

// ==================== Server Builder ====================

const serverTemplates = {
    database: (config) => `"""
MCP Database Server
Generated by Day 20 Demo
"""
from mcp.server import Server
from mcp.types import Tool, TextContent
import ${config.dbType === 'sqlite' ? 'sqlite3' : 'asyncpg'}
import json
import re
${config.logging ? 'import logging\n\nlogging.basicConfig(level=logging.INFO)\nlogger = logging.getLogger("db-mcp")' : ''}

server = Server("database-server")
DB_PATH = "${config.dbPath}"
READ_ONLY = ${config.readOnly ? 'True' : 'False'}
ROW_LIMIT = ${config.rowLimit}

${config.validate ? `def validate_sql(sql: str) -> tuple[bool, str]:
    """Validate SQL query for safety."""
    sql_upper = sql.strip().upper()

    if READ_ONLY and not sql_upper.startswith("SELECT"):
        return False, "Only SELECT queries allowed in read-only mode"

    dangerous = ["DROP", "TRUNCATE", "ALTER", "ATTACH", "DETACH"]
    for keyword in dangerous:
        if keyword in sql_upper:
            return False, f"Dangerous keyword: {keyword}"

    return True, ""
` : ''}
@server.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="query",
            description="Execute a SQL query",
            inputSchema={
                "type": "object",
                "properties": {
                    "sql": {"type": "string", "description": "SQL query"}
                },
                "required": ["sql"]
            }
        ),${config.schema ? `
        Tool(
            name="list_tables",
            description="List all tables in the database",
            inputSchema={"type": "object", "properties": {}}
        ),
        Tool(
            name="describe_table",
            description="Get schema for a table",
            inputSchema={
                "type": "object",
                "properties": {
                    "table": {"type": "string", "description": "Table name"}
                },
                "required": ["table"]
            }
        ),` : ''}
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    ${config.logging ? 'logger.info(f"Tool call: {name}, args: {arguments}")' : ''}

    conn = ${config.dbType === 'sqlite' ? `sqlite3.connect(DB_PATH${config.readOnly ? ', uri=True' : ''})
    conn.row_factory = sqlite3.Row` : 'await asyncpg.connect(DB_PATH)'}

    try:
        if name == "query":
            sql = arguments.get("sql", "")
            ${config.validate ? `
            valid, error = validate_sql(sql)
            if not valid:
                return [TextContent(type="text", text=error, isError=True)]
            ` : ''}
            # Add LIMIT if not present
            if "LIMIT" not in sql.upper():
                sql = sql.rstrip(";") + f" LIMIT {ROW_LIMIT}"

            cursor = conn.execute(sql)
            rows = [dict(row) for row in cursor.fetchall()]

            return [TextContent(type="text", text=json.dumps({
                "row_count": len(rows),
                "rows": rows
            }, indent=2, default=str))]
        ${config.schema ? `
        elif name == "list_tables":
            cursor = conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            )
            tables = [row["name"] for row in cursor.fetchall()]
            return [TextContent(type="text", text=json.dumps({"tables": tables}))]

        elif name == "describe_table":
            table = arguments.get("table", "")
            if not re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", table):
                return [TextContent(type="text", text="Invalid table name", isError=True)]

            cursor = conn.execute(f"PRAGMA table_info({table})")
            columns = [{"name": r["name"], "type": r["type"]} for r in cursor]
            return [TextContent(type="text", text=json.dumps({"columns": columns}))]
        ` : ''}
    except Exception as e:
        ${config.logging ? 'logger.error(f"Error: {e}")' : ''}
        return [TextContent(type="text", text=str(e), isError=True)]
    finally:
        conn.close()

if __name__ == "__main__":
    import asyncio
    asyncio.run(server.run())`,

    api: (config) => `"""
MCP API Wrapper Server
Generated by Day 20 Demo
"""
from mcp.server import Server
from mcp.types import Tool, TextContent
import httpx
import json
import os
import time
${config.rateLimit ? 'from dataclasses import dataclass, field' : ''}

server = Server("${config.apiName}-server")
API_KEY = os.environ.get("${config.apiName.toUpperCase()}_API_KEY", "")
BASE_URL = "${config.apiUrl}"
${config.caching ? `CACHE_TTL = ${config.cacheTtl}` : ''}

${config.rateLimit ? `@dataclass
class RateLimiter:
    calls_per_minute: int = 30
    minute_calls: list = field(default_factory=list)

    def check(self) -> tuple[bool, str]:
        now = time.time()
        self.minute_calls = [t for t in self.minute_calls if t > now - 60]
        if len(self.minute_calls) >= self.calls_per_minute:
            return False, "Rate limit exceeded"
        return True, ""

    def record(self):
        self.minute_calls.append(time.time())

rate_limiter = RateLimiter()
` : ''}
${config.caching ? `cache: dict = {}

def get_cached(key: str):
    if key in cache and time.time() < cache[key]["expires"]:
        return cache[key]["data"]
    return None

def set_cached(key: str, data: dict):
    cache[key] = {"data": data, "expires": time.time() + CACHE_TTL}
` : ''}
class APIClient:
    def __init__(self):
        self.client = httpx.AsyncClient(timeout=15.0)

    async def request(self, method: str, path: str, params: dict = None) -> dict:
        ${config.rateLimit ? `allowed, error = rate_limiter.check()
        if not allowed:
            raise Exception(error)
        rate_limiter.record()
        ` : ''}
        ${config.caching ? `cache_key = f"{method}:{path}:{json.dumps(params or {})}"
        cached = get_cached(cache_key)
        if cached:
            return cached
        ` : ''}
        headers = ${config.authType === 'header' ? '{"Authorization": f"Bearer {API_KEY}"}' :
                    config.authType === 'query' ? '{}' : '{}'}
        ${config.authType === 'query' ? 'params = {**(params or {}), "appid": API_KEY}' : ''}

        response = await self.client.request(method, f"{BASE_URL}{path}", params=params, headers=headers)
        response.raise_for_status()
        data = response.json()
        ${config.caching ? `set_cached(cache_key, data)` : ''}
        return data

api = APIClient()

@server.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="get_data",
            description="Fetch data from the ${config.apiName} API",
            inputSchema={
                "type": "object",
                "properties": {
                    "endpoint": {"type": "string", "description": "API endpoint path"},
                    "params": {"type": "object", "description": "Query parameters"}
                },
                "required": ["endpoint"]
            }
        )
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    try:
        if name == "get_data":
            endpoint = arguments.get("endpoint", "/")
            params = arguments.get("params", {})

            data = await api.request("GET", endpoint, params)
            return [TextContent(type="text", text=json.dumps(data, indent=2))]

    except httpx.HTTPError as e:
        return [TextContent(type="text", text=f"API error: {e}", isError=True)]
    except Exception as e:
        return [TextContent(type="text", text=str(e), isError=True)]

if __name__ == "__main__":
    import asyncio
    asyncio.run(server.run())`,

    file: (config) => `"""
MCP File System Server
Generated by Day 20 Demo
"""
from mcp.server import Server
from mcp.types import Tool, Resource, TextContent
import os
import json
${config.hash ? 'import hashlib' : ''}
from pathlib import Path

server = Server("file-server")
SANDBOX_ROOT = Path("${config.root}").resolve()
MAX_FILE_SIZE = ${config.maxSize * 1024 * 1024}  # ${config.maxSize}MB
MAX_LINES = ${config.maxLines}
ALLOWED_EXTENSIONS = {${config.extensions.split(',').map(e => `"${e.trim()}"`).join(', ')}}

def resolve_path(path: str) -> Path | None:
    """Resolve path safely within sandbox."""
    try:
        if path.startswith("/"):
            full_path = Path(path).resolve()
        else:
            full_path = (SANDBOX_ROOT / path).resolve()

        # Security: Ensure path is within sandbox
        if not str(full_path).startswith(str(SANDBOX_ROOT)):
            return None

        return full_path
    except (ValueError, OSError):
        return None

def is_allowed_file(path: Path) -> bool:
    """Check if file extension is allowed."""
    return path.suffix.lower() in ALLOWED_EXTENSIONS

@server.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="list_directory",
            description="List files in a directory",
            inputSchema={
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "Directory path"}
                }
            }
        ),
        Tool(
            name="read_file",
            description="Read contents of a text file",
            inputSchema={
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "File path"},
                    "start_line": {"type": "integer", "description": "Start line"},
                    "max_lines": {"type": "integer", "description": "Max lines to read"}
                },
                "required": ["path"]
            }
        ),${config.search ? `
        Tool(
            name="search_files",
            description="Search for files by name",
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Search query"},
                    "pattern": {"type": "string", "description": "Glob pattern"}
                },
                "required": ["query"]
            }
        ),` : ''}${config.hash ? `
        Tool(
            name="file_info",
            description="Get file metadata and hash",
            inputSchema={
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "File path"}
                },
                "required": ["path"]
            }
        ),` : ''}
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    try:
        if name == "list_directory":
            path_str = arguments.get("path", "")
            path = resolve_path(path_str) if path_str else SANDBOX_ROOT

            if not path or not path.is_dir():
                return [TextContent(type="text", text="Directory not found", isError=True)]

            items = []
            for item in sorted(path.iterdir())[:100]:
                rel_path = item.relative_to(SANDBOX_ROOT)
                items.append({
                    "name": item.name,
                    "path": str(rel_path),
                    "type": "directory" if item.is_dir() else "file"
                })

            return [TextContent(type="text", text=json.dumps({"items": items}, indent=2))]

        elif name == "read_file":
            path = resolve_path(arguments.get("path", ""))
            if not path or not path.is_file():
                return [TextContent(type="text", text="File not found", isError=True)]

            if path.stat().st_size > MAX_FILE_SIZE:
                return [TextContent(type="text", text="File too large", isError=True)]

            if not is_allowed_file(path):
                return [TextContent(type="text", text="File type not allowed", isError=True)]

            start_line = arguments.get("start_line", 1)
            max_lines = min(arguments.get("max_lines", MAX_LINES), MAX_LINES)

            with open(path, "r", encoding="utf-8", errors="replace") as f:
                lines = f.readlines()

            selected = lines[start_line-1:start_line-1+max_lines]

            return [TextContent(type="text", text=json.dumps({
                "path": str(path.relative_to(SANDBOX_ROOT)),
                "total_lines": len(lines),
                "content": "".join(selected)
            }, indent=2))]
        ${config.search ? `
        elif name == "search_files":
            query = arguments.get("query", "").lower()
            pattern = arguments.get("pattern", "*")

            results = []
            for path in SANDBOX_ROOT.rglob(pattern):
                if path.is_file() and query in path.name.lower():
                    results.append(str(path.relative_to(SANDBOX_ROOT)))
                    if len(results) >= 50:
                        break

            return [TextContent(type="text", text=json.dumps({"results": results}, indent=2))]
        ` : ''}${config.hash ? `
        elif name == "file_info":
            path = resolve_path(arguments.get("path", ""))
            if not path or not path.exists():
                return [TextContent(type="text", text="Path not found", isError=True)]

            stat = path.stat()
            info = {
                "name": path.name,
                "size": stat.st_size,
                "modified": stat.st_mtime
            }

            if path.is_file() and stat.st_size < MAX_FILE_SIZE:
                with open(path, "rb") as f:
                    info["sha256"] = hashlib.sha256(f.read()).hexdigest()[:16]

            return [TextContent(type="text", text=json.dumps(info, indent=2, default=str))]
        ` : ''}
    except Exception as e:
        return [TextContent(type="text", text=str(e), isError=True)]

if __name__ == "__main__":
    import asyncio
    asyncio.run(server.run())`
};

// Initialize builder
function initBuilder() {
    const typeCards = document.querySelectorAll('.server-type-card');
    const configPanels = document.querySelectorAll('.config-panel');

    typeCards.forEach(card => {
        card.addEventListener('click', () => {
            const type = card.dataset.type;

            typeCards.forEach(c => c.classList.remove('active'));
            card.classList.add('active');

            configPanels.forEach(p => p.classList.remove('active'));
            document.querySelector(`[data-config="${type}"]`).classList.add('active');

            updateServerCode();
        });
    });

    // Listen for config changes
    document.querySelectorAll('#builder-config input, #builder-config select').forEach(el => {
        el.addEventListener('change', updateServerCode);
        el.addEventListener('input', updateServerCode);
    });

    // Toggle buttons
    document.querySelectorAll('.toggle').forEach(toggle => {
        toggle.addEventListener('click', () => {
            const group = toggle.closest('.toggle-group');
            group.querySelectorAll('.toggle').forEach(t => t.classList.remove('active'));
            toggle.classList.add('active');
        });
    });

    // Copy and download
    document.getElementById('copy-code').addEventListener('click', () => {
        const code = document.getElementById('server-code').textContent;
        copyToClipboard(code);
    });

    document.getElementById('download-code').addEventListener('click', () => {
        const code = document.getElementById('server-code').textContent;
        const blob = new Blob([code], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'mcp_server.py';
        a.click();
        URL.revokeObjectURL(url);
    });

    updateServerCode();
}

function getBuilderConfig() {
    const activeType = document.querySelector('.server-type-card.active').dataset.type;

    if (activeType === 'database') {
        return {
            type: 'database',
            dbType: document.getElementById('db-type').value,
            dbPath: document.getElementById('db-path').value,
            readOnly: document.querySelector('input[name="db-mode"]:checked').value === 'readonly',
            rowLimit: document.getElementById('db-limit').value,
            validate: document.getElementById('db-validate').checked,
            logging: document.getElementById('db-logging').checked,
            schema: document.getElementById('db-schema').checked
        };
    } else if (activeType === 'api') {
        return {
            type: 'api',
            apiName: document.getElementById('api-name').value,
            apiUrl: document.getElementById('api-url').value,
            authType: document.getElementById('api-auth').value,
            cacheTtl: document.getElementById('api-cache').value,
            rateLimit: document.getElementById('api-ratelimit').checked,
            caching: document.getElementById('api-caching').checked,
            retry: document.getElementById('api-retry').checked
        };
    } else {
        return {
            type: 'file',
            root: document.getElementById('file-root').value,
            maxSize: document.getElementById('file-maxsize').value,
            extensions: document.getElementById('file-extensions').value,
            maxLines: document.getElementById('file-maxlines').value,
            search: document.getElementById('file-search').checked,
            hash: document.getElementById('file-hash').checked,
            readOnly: document.getElementById('file-readonly').checked
        };
    }
}

function updateServerCode() {
    const config = getBuilderConfig();
    const code = serverTemplates[config.type](config);

    const codeEl = document.getElementById('server-code');
    codeEl.textContent = code;
    Prism.highlightElement(codeEl);
}

// ==================== Security Checker ====================

const securityPatterns = {
    'input-validation': {
        patterns: [/validate|check|verify|sanitize/i, /arguments\.get|args\[/],
        required: 1
    },
    'sql-injection': {
        patterns: [/execute\(sql,\s*params|execute\(sql,\s*\[|\?|%s|\$\d/],
        antipatterns: [/f".*{.*}.*"|f'.*{.*}.*'/],
        message: 'Uses parameterized queries'
    },
    'path-traversal': {
        patterns: [/resolve\(\)|\.resolve\(|startswith|is_relative_to/i],
        message: 'Validates file paths'
    },
    'credential-exposure': {
        antipatterns: [/api_key\s*=\s*["'][^"']+["']|password\s*=\s*["'][^"']+["']/i],
        patterns: [/environ|getenv|os\.environ/],
        message: 'Uses environment variables'
    },
    'error-handling': {
        patterns: [/try:|except|catch|finally/],
        required: 2
    },
    'rate-limiting': {
        patterns: [/rate.?limit|throttle|calls_per/i],
        optional: true
    },
    'logging': {
        patterns: [/logger\.|logging\.|log\(/i]
    },
    'resource-limits': {
        patterns: [/limit|max_|maximum/i],
        required: 1
    }
};

function initSecurity() {
    document.getElementById('analyze-security').addEventListener('click', analyzeSecurity);

    // Pre-fill with sample code
    document.getElementById('security-code').value = `# Paste your MCP server code here to analyze security
# Example patterns that will be detected:

# Good: Environment variables for credentials
API_KEY = os.environ.get("API_KEY", "")

# Good: Parameterized queries
cursor.execute(sql, params)

# Good: Path validation
if not str(full_path).startswith(str(SANDBOX_ROOT)):
    return None

# Good: Error handling
try:
    result = process_data()
except Exception as e:
    logger.error(f"Error: {e}")

# Good: Resource limits
if "LIMIT" not in sql.upper():
    sql = sql + " LIMIT 100"
`;
}

function analyzeSecurity() {
    const code = document.getElementById('security-code').value;
    const results = {};
    let passed = 0;
    let total = 0;

    for (const [check, config] of Object.entries(securityPatterns)) {
        if (config.optional && !code.match(config.patterns?.[0])) {
            results[check] = 'pending';
            continue;
        }

        total++;
        let pass = true;

        // Check for antipatterns (bad practices)
        if (config.antipatterns) {
            for (const pattern of config.antipatterns) {
                if (pattern.test(code)) {
                    pass = false;
                    break;
                }
            }
        }

        // Check for required patterns
        if (pass && config.patterns) {
            const required = config.required || 1;
            let found = 0;
            for (const pattern of config.patterns) {
                if (pattern.test(code)) found++;
            }
            if (found < required) pass = false;
        }

        results[check] = pass ? 'pass' : 'fail';
        if (pass) passed++;
    }

    // Update UI
    const score = total > 0 ? Math.round((passed / total) * 100) : 0;
    const scoreEl = document.getElementById('score-value');
    const circleEl = document.getElementById('score-circle');

    scoreEl.textContent = score;
    circleEl.style.setProperty('--score', score);
    circleEl.className = 'score-circle ' + (score >= 80 ? 'good' : score >= 50 ? 'warning' : 'danger');

    // Update checklist
    document.querySelectorAll('.check-item').forEach(item => {
        const check = item.dataset.check;
        const result = results[check];
        item.className = 'check-item ' + result;
    });
}

// ==================== Test Playground ====================

const playgroundData = {
    database: {
        tools: [
            { name: 'query', icon: '📊', args: [{ name: 'sql', type: 'text', placeholder: 'SELECT * FROM users LIMIT 5' }] },
            { name: 'list_tables', icon: '📋', args: [] },
            { name: 'describe_table', icon: '🔍', args: [{ name: 'table', type: 'text', placeholder: 'users' }] }
        ],
        responses: {
            query: { row_count: 3, rows: [{ id: 1, name: 'Alice' }, { id: 2, name: 'Bob' }, { id: 3, name: 'Charlie' }] },
            list_tables: { tables: ['users', 'orders', 'products', 'sessions'] },
            describe_table: { table: 'users', columns: [{ name: 'id', type: 'INTEGER' }, { name: 'name', type: 'TEXT' }, { name: 'email', type: 'TEXT' }] }
        }
    },
    weather: {
        tools: [
            { name: 'get_weather', icon: '🌤️', args: [{ name: 'location', type: 'text', placeholder: 'London' }] },
            { name: 'get_forecast', icon: '📅', args: [{ name: 'location', type: 'text', placeholder: 'New York' }] }
        ],
        responses: {
            get_weather: { location: 'London', temp: 15, conditions: 'Partly cloudy', humidity: 72 },
            get_forecast: { location: 'New York', forecast: [{ day: 'Mon', high: 22, low: 14 }, { day: 'Tue', high: 25, low: 16 }] }
        }
    },
    files: {
        tools: [
            { name: 'list_directory', icon: '📁', args: [{ name: 'path', type: 'text', placeholder: '/' }] },
            { name: 'read_file', icon: '📄', args: [{ name: 'path', type: 'text', placeholder: 'readme.md' }] },
            { name: 'search_files', icon: '🔍', args: [{ name: 'query', type: 'text', placeholder: 'config' }] }
        ],
        responses: {
            list_directory: { items: [{ name: 'src', type: 'directory' }, { name: 'readme.md', type: 'file' }, { name: 'config.json', type: 'file' }] },
            read_file: { path: 'readme.md', total_lines: 25, content: '# My Project\\n\\nThis is a sample project...' },
            search_files: { results: ['config.json', 'src/config.py', 'tests/test_config.py'] }
        }
    }
};

let currentServer = 'database';
let currentTool = null;

function initPlayground() {
    // Server selection
    document.querySelectorAll('.playground-server').forEach(server => {
        server.addEventListener('click', () => {
            document.querySelectorAll('.playground-server').forEach(s => s.classList.remove('active'));
            server.classList.add('active');
            currentServer = server.dataset.server;
            currentTool = null;
            updateToolsList();
            updateToolForm();
        });
    });

    // Execute button
    document.getElementById('execute-tool').addEventListener('click', executeTool);

    // Clear console
    document.getElementById('clear-console').addEventListener('click', () => {
        document.getElementById('console-output').innerHTML = `
            <div class="console-welcome">
                <p>Console cleared.</p>
            </div>
        `;
    });

    updateToolsList();
}

function updateToolsList() {
    const toolsList = document.getElementById('tools-list');
    const serverData = playgroundData[currentServer];

    toolsList.innerHTML = serverData.tools.map(tool => `
        <div class="tool-item" data-tool="${tool.name}">
            <span class="tool-icon">${tool.icon}</span>
            <span class="tool-name">${tool.name}</span>
        </div>
    `).join('');

    // Tool selection
    toolsList.querySelectorAll('.tool-item').forEach(item => {
        item.addEventListener('click', () => {
            document.querySelectorAll('.tool-item').forEach(t => t.classList.remove('active'));
            item.classList.add('active');
            currentTool = item.dataset.tool;
            updateToolForm();
        });
    });
}

function updateToolForm() {
    const form = document.getElementById('tool-form');
    const executeBtn = document.getElementById('execute-tool');

    if (!currentTool) {
        form.innerHTML = '<span style="color: var(--text-muted)">Select a tool to configure arguments</span>';
        executeBtn.disabled = true;
        return;
    }

    const serverData = playgroundData[currentServer];
    const tool = serverData.tools.find(t => t.name === currentTool);

    if (tool.args.length === 0) {
        form.innerHTML = '<span style="color: var(--text-muted)">No arguments required</span>';
    } else {
        form.innerHTML = tool.args.map(arg => `
            <div class="form-group">
                <label>${arg.name}</label>
                <input type="${arg.type}" id="arg-${arg.name}" placeholder="${arg.placeholder}">
            </div>
        `).join('');
    }

    executeBtn.disabled = false;
}

function executeTool() {
    if (!currentTool) return;

    const serverData = playgroundData[currentServer];
    const tool = serverData.tools.find(t => t.name === currentTool);
    const consoleOutput = document.getElementById('console-output');

    // Gather arguments
    const args = {};
    tool.args.forEach(arg => {
        const input = document.getElementById(`arg-${arg.name}`);
        if (input && input.value) {
            args[arg.name] = input.value;
        }
    });

    // Show request
    const requestMsg = {
        jsonrpc: '2.0',
        id: Date.now(),
        method: 'tools/call',
        params: {
            name: currentTool,
            arguments: args
        }
    };

    consoleOutput.innerHTML += `
        <div class="console-message request">
            <strong>→ Request</strong>
            <pre>${JSON.stringify(requestMsg, null, 2)}</pre>
        </div>
    `;

    // Simulate response
    setTimeout(() => {
        const response = serverData.responses[currentTool];
        const responseMsg = {
            jsonrpc: '2.0',
            id: requestMsg.id,
            result: {
                content: [{
                    type: 'text',
                    text: JSON.stringify(response, null, 2)
                }]
            }
        };

        consoleOutput.innerHTML += `
            <div class="console-message response">
                <strong>← Response</strong>
                <pre>${JSON.stringify(responseMsg, null, 2)}</pre>
            </div>
        `;

        consoleOutput.scrollTop = consoleOutput.scrollHeight;
    }, 300);
}

// ==================== Compose Tab ====================

const serverConfigs = {
    database: { icon: '🗄️', name: 'Database', command: 'python', args: ['-m', 'mcp_servers.database'] },
    api: { icon: '🌐', name: 'API', command: 'python', args: ['-m', 'mcp_servers.api'] },
    files: { icon: '📁', name: 'Files', command: 'python', args: ['-m', 'mcp_servers.files'] },
    search: { icon: '🔍', name: 'Search', command: 'python', args: ['-m', 'mcp_servers.search'] },
    cache: { icon: '⚡', name: 'Cache', command: 'python', args: ['-m', 'mcp_servers.cache'] }
};

function initCompose() {
    const palette = document.querySelectorAll('.palette-item');
    const slots = document.querySelectorAll('.client-slot');

    palette.forEach(item => {
        item.addEventListener('dragstart', (e) => {
            e.dataTransfer.setData('server', item.dataset.server);
        });
    });

    slots.forEach(slot => {
        slot.addEventListener('dragover', (e) => {
            e.preventDefault();
            slot.classList.add('dragover');
        });

        slot.addEventListener('dragleave', () => {
            slot.classList.remove('dragover');
        });

        slot.addEventListener('drop', (e) => {
            e.preventDefault();
            slot.classList.remove('dragover');

            const server = e.dataTransfer.getData('server');
            if (server && slot.classList.contains('empty')) {
                fillSlot(slot, server);
            }
        });
    });

    document.getElementById('add-slot').addEventListener('click', addSlot);
    document.getElementById('clear-canvas').addEventListener('click', clearCanvas);
    document.getElementById('copy-config').addEventListener('click', () => {
        const code = document.getElementById('compose-output').textContent;
        copyToClipboard(code);
    });

    updateComposeConfig();
}

function fillSlot(slot, serverType) {
    const config = serverConfigs[serverType];

    slot.classList.remove('empty');
    slot.classList.add('filled');
    slot.innerHTML = `
        <div class="slot-content">
            <div class="slot-icon">${config.icon}</div>
            <div class="slot-name">${config.name}</div>
        </div>
        <button class="slot-remove" onclick="clearSlot(this.parentElement)">×</button>
    `;
    slot.dataset.server = serverType;

    updateComposeConfig();
}

function clearSlot(slot) {
    slot.classList.remove('filled');
    slot.classList.add('empty');
    slot.innerHTML = '<span class="slot-label">Drop server here</span>';
    delete slot.dataset.server;
    updateComposeConfig();
}

function addSlot() {
    const container = document.getElementById('canvas-clients');
    const slotCount = container.querySelectorAll('.client-slot').length;

    if (slotCount >= 6) {
        showToast('Maximum 6 servers');
        return;
    }

    const slot = document.createElement('div');
    slot.className = 'client-slot empty';
    slot.dataset.slot = slotCount + 1;
    slot.innerHTML = '<span class="slot-label">Drop server here</span>';

    slot.addEventListener('dragover', (e) => {
        e.preventDefault();
        slot.classList.add('dragover');
    });

    slot.addEventListener('dragleave', () => {
        slot.classList.remove('dragover');
    });

    slot.addEventListener('drop', (e) => {
        e.preventDefault();
        slot.classList.remove('dragover');

        const server = e.dataTransfer.getData('server');
        if (server && slot.classList.contains('empty')) {
            fillSlot(slot, server);
        }
    });

    container.appendChild(slot);
}

function clearCanvas() {
    document.querySelectorAll('.client-slot').forEach((slot, index) => {
        if (index < 3) {
            clearSlot(slot);
        } else {
            slot.remove();
        }
    });
    updateComposeConfig();
}

function updateComposeConfig() {
    const slots = document.querySelectorAll('.client-slot.filled');
    const config = { mcpServers: {} };

    slots.forEach(slot => {
        const serverType = slot.dataset.server;
        const serverConfig = serverConfigs[serverType];

        config.mcpServers[serverType] = {
            command: serverConfig.command,
            args: serverConfig.args,
            env: {}
        };
    });

    const codeEl = document.getElementById('compose-output');
    codeEl.textContent = JSON.stringify(config, null, 2);
    Prism.highlightElement(codeEl);
}

// Make clearSlot global for onclick
window.clearSlot = clearSlot;

// Initialize all tabs
document.addEventListener('DOMContentLoaded', () => {
    initBuilder();
    initSecurity();
    initPlayground();
    initCompose();
});
